version: '3'
services:

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    user: 1000:1000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${MB_User}
      MB_DB_PASS: ${MB_Password}
      MB_DB_HOST: postgres
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
        - postgres
    volumes:
      - /metabase_data:/metabase-data
    ports:
      - 3000:3000
  postgres:
    image: postgres:15.2-alpine
    container_name: postgresql
    restart: always
    user: 1000:1000
    environment:
      POSTGRES_USER: ${PG_User}
      POSTGRES_PASSWORD: ${PG_Password}
      PGDATA: /data/postgres
    volumes:
        - /pg_data:/data/postgres
    ports:
      - 5432:5432

volumes:
  metabase_data:
  pg_data:

  # db:
  # image: postgres:15
  # container_name: postgresql_metabase
  # restart: always
  # environment:
  #   - POSTGRES_DB: metabase
  #   - POSTGRES_USER: metabase
  #   - POSTGRES_PASSWORD: db_password
  # volumes:
  #     - db_data:/var/lib/postgresql/data
  # ports:
  #   - 5432:5432

